"""Update User model: add confirmed field

Revision ID: 7241a212ba34
Revises: 6d82f0749e15
Create Date: 2025-03-30 18:06:26.093452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7241a212ba34'
down_revision: Union[str, None] = '6d82f0749e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET confirmed = TRUE WHERE confirmed IS NULL")
    op.alter_column("users", "confirmed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
